# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261799725ef4267ae966be4066ef69873508fe3f4dfca2979954f45df785f6a0e41610a52ef80cf15b5330058251ae22724da48b98b971adad370fd961c6638b

test:
  secret_key_base: 6c10622c332e823aae85aca6e2e1e8cdddf9939de05afa634dbe23c10dc549f08c0dd8df394103984b407ac2e425bcb351ed571c25afd129973e59b94294c747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
